version: "3"
services:
  bitcoind:
    image: zquestz/bitcoin-cash-node
    # specify additional command line arguments here
    command: bitcoind
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "getblockchaininfo"]
    ports:
      # change to 18333 if running testnet
      - "8333:8333"
      # JSON-RPC
      - "8332:8332"
      # ZMQ
      - "28332:28332"
    volumes:
      # using a custom path for data dir
      - ./data:/data
      # using a custom path for custom bitcoin.conf
      - ./bitcoin.conf:/data/bitcoin.conf
    networks:
      - bitcoin
  bitcoin-cli:
    image: zquestz/bitcoin-cash-node
    entrypoint: ["/entrypoint.sh", "bitcoin-cli"]
    command: ""
    depends_on:
      - bitcoind
    network_mode: service:bitcoind
    volumes:
      # using a custom path for custom bitcoin.conf
      - ./bitcoin.conf:/data/bitcoin.conf

networks:
  bitcoin:
